// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pomo.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PomoDbContext))]
    partial class PomoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pomo.Data.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BuiltAfterMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("built_after_minutes");

                    b.Property<DateTimeOffset>("BuiltAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("built_at");

                    b.Property<int>("GridX")
                        .HasColumnType("integer")
                        .HasColumnName("grid_x");

                    b.Property<int>("GridY")
                        .HasColumnType("integer")
                        .HasColumnName("grid_y");

                    b.Property<string>("KindId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_buildings");

                    b.HasIndex("UserId", "GridX", "GridY")
                        .IsUnique()
                        .HasDatabaseName("ix_buildings_user_id_grid_x_grid_y");

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("Pomo.Data.Entities.FocusCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CityCoins")
                        .HasColumnType("bigint")
                        .HasColumnName("city_coins");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_seconds");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<long>("FocusCoins")
                        .HasColumnType("bigint")
                        .HasColumnName("focus_coins");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("KeysEarned")
                        .HasColumnType("integer")
                        .HasColumnName("keys_earned");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<int>("PauseCount")
                        .HasColumnType("integer")
                        .HasColumnName("pause_count");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("TimeZoneOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_zone_offset_minutes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_focus_cycles");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_focus_cycles_user_id_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_focus_cycles_user_id_started_at");

                    b.ToTable("focus_cycles", (string)null);
                });

            modelBuilder.Entity("Pomo.Data.Entities.PlayerState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("BaselineSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("baseline_seconds");

                    b.Property<int>("BreakLimitSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("break_limit_seconds");

                    b.Property<long>("Coins")
                        .HasColumnType("bigint")
                        .HasColumnName("coins");

                    b.Property<int>("Cycle")
                        .HasColumnType("integer")
                        .HasColumnName("cycle");

                    b.Property<int>("FocusTargetSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("focus_target_seconds");

                    b.Property<int>("HighScoreSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("high_score_seconds");

                    b.Property<int>("Keys")
                        .HasColumnType("integer")
                        .HasColumnName("keys");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_minutes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("UserId")
                        .HasName("pk_player_states");

                    b.ToTable("player_states", (string)null);
                });

            modelBuilder.Entity("Pomo.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mfa_secret");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_users_external_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Pomo.Data.Entities.Building", b =>
                {
                    b.HasOne("Pomo.Data.Entities.User", "User")
                        .WithMany("Buildings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_buildings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pomo.Data.Entities.FocusCycle", b =>
                {
                    b.HasOne("Pomo.Data.Entities.User", "User")
                        .WithMany("Cycles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_focus_cycles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pomo.Data.Entities.PlayerState", b =>
                {
                    b.HasOne("Pomo.Data.Entities.User", "User")
                        .WithOne("State")
                        .HasForeignKey("Pomo.Data.Entities.PlayerState", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_states_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pomo.Data.Entities.User", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Cycles");

                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
